blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('students', 'StudentController');
Route::resource('lectures', 'LectureController');
Route::resource('grades', 'GradeController');

blog/app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{

    protected $table = 'students';

    protected $guarded = ['id'];

    public function grades(){
        return $this->hasMany('App\Grade', 'student_id', 'id')->get();
    }
    public function allGrades(){
        return $this->belongsToMany(
            'App\Grade',
            'grades',
            'lectures_id',
            'students_id'
        )->get();
    }
}

blog/app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentsRequest;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class StudentController extends Controller
{
    public function __construct()
    {
        $this->middleware('teacher')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::orderBy('surname', 'ASC')->get();

        return view('students.index', [
            'students' => $students,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentsRequest $request)
    {
        Student::create($request->all());

        session()->flash('message', 'Added new student');
        session()->flash('message-class', 'alert-success');

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        $grades = $student->grades()->where('student_id', $student->id);

        return view('students.show', [
            'student' => $student,
            'grades' => $grades
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('students.edit', [
            'student' => $student,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Student $student)
    {
        $student->update($request->all());

        session()->flash('message', 'Updated info for student');
        session()->flash('message-class', 'alert-success');

        return redirect()->route('students.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();

        session()->flash('message', 'Student was deleted');
        session()->flash('message-class', 'alert-danger');

        return redirect()->back();
    }
}

blog/resources/views/students/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-md-center">
                <h1>{{__('Adding new student to your ranks')}}</h1>
            </div>
            <div class="col-md-6">
                <form method="post" action="{{route('students.store')}}">
                    @csrf
                    <div>
                        <label>{{__('Name')}}:</label>
                        <input class="form-control @error('name') is-invalid @enderror" required name="name" type="text" value="{{ old('name') }}">
                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div>
                        <label>{{__('Surname')}}:</label>
                        <input class="form-control @error('surname') is-invalid @enderror" required name="surname" type="text" value="{{ old('surname') }}">
                        @error('surname')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div>
                        <label>{{__('Email')}}:</label>
                        <input class="form-control @error('email') is-invalid @enderror" required name="email" type="email" value="{{ old('email') }}">
                        @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div>
                        <label>{{__('Phone')}}:</label>
                        <input class="form-control @error('phone') is-invalid @enderror" required name="phone" type="text" value="{{ old('phone') }}">
                        @error('phone')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div>
                        <input class="col-md-6 mt-3 float-md-right btn-success form-control" type="submit" value="{{__('Add')}}">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/students/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-md-center">
                <h1>{{__('Editing student')}}: {{ $student->surname }} {{ $student->name }}</h1>
            </div>
            <div class="col-md-6">
                <form method="post" action="{{route('students.update', [$student->id])}}">
                    @csrf
                    @method('put')
                    <div>
                        <label>{{__('Name')}}:</label>
                        <input class="form-control" name="name" type="text" value="{{$student->name}}">
                    </div>
                    <div>
                        <label>{{__('Surname')}}:</label>
                        <input class="form-control" name="surname" type="text" value="{{$student->surname}}">
                    </div>
                    <div>
                        <label>{{__('Email')}}:</label>
                        <input class="form-control" name="email" type="email" value="{{$student->email}}">
                    </div>
                    <div>
                        <label>{{__('Phone')}}:</label>
                        <input class="form-control" name="phone" type="text" value="{{$student->phone}}">
                    </div>
                    <div>
                        <input class="col-md-6 mt-3 float-md-right btn-success form-control" type="submit" value="{{__('Update')}}">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/students/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>
                    {{__('Students')}} ({{$students->count()}})
                </h1>
                <table id="table_test" class="table">
                    <thead>
                        <th>
                            {{__('ID')}}
                        </th>
                        <th>
                            {{__('Surname')}}
                        </th>
                        <th>
                            {{__('Name')}}
                        </th>
                        <th>
                            {{__('Email')}}
                        </th>
                        <th>
                            {{__('Phone')}}
                        </th>
                        @if(isset(Auth::user()->role) && Auth::user()->role == 'teacher')
                        <th>
                            {{__('Edit')}}
                        </th>
                        <th>
                            {{__('Delete')}}
                        </th>
                        @endif
                    </thead>
                    <tbody>
                        @foreach($students as $student)
                            <tr>
                                <td>
                                    <a href="{{route('students.show', [$student->id])}}">
                                        {{ $student->id }}
                                    </a>
                                </td>
                                <td>
                                    {{ $student->surname }}
                                </td>
                                <td>
                                    {{ $student->name }}
                                </td>
                                <td>
                                    {{ $student->email }}
                                </td>
                                <td>
                                    {{ $student->phone }}
                                </td>
                                @if(isset(Auth::user()->role) && Auth::user()->role == 'teacher')
                                <td>
                                    <form method="get" action="{{ route('students.edit', [$student->id]) }}">
                                        <input class="btn btn-success" type="submit" value="Edit">
                                    </form>
                                </td>
                                <td>
                                    <form method="post" action="{{ route('students.destroy', [$student->id]) }}">
                                        @csrf
                                        @method('delete')
                                        <input class="btn btn-danger" type="submit" value="X">
                                    </form>
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/students/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h3>{{__('Student')}} {{ $student->surname }} {{ $student->name }} {{__('profile')}}</h3>
                <ul>
                    <li>
                        {{__('Name')}}: {{$student->name}}
                    </li>
                    <li>
                        {{__('Surname')}}: {{$student->surname}}
                    </li>
                    <li>
                        {{__('Email')}}: {{$student->email}}
                    </li>
                    <li>
                        {{__('Phone')}}: {{$student->phone}}
                    </li>
                </ul>
            </div>
            <div class="col-md-6">
                <h4>{{__('Grades')}}({{ $student->grades()->count() }}):</h4>
                <div>
                    <table class="table">
                        <thead>
                            <th>
                                {{__('Lecture')}}
                            </th>
                            <th>
                                {{__('Grade')}}
                            </th>
                            <th>
                                {{__('When')}}
                            </th>
                        </thead>
                        <tbody>

                            @foreach($student->grades() as $grade)
                                <tr>
                                @foreach($grade->lecture() as $lecture)
                                    <td>
                                        {{$lecture->name}}
                                    </td>
                                @endforeach
                                    <td>
                                        {{$grade->grade}}
                                    </td>
                                    <td>
                                        {{$grade->created_at}}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection