blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('students', 'StudentController');
Route::resource('lectures', 'LectureController');
Route::resource('grades', 'GradeController');

blog/app/Grade.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    protected $table = 'grades';

    public function allGrades(){
        return $this->belongsToMany(
            'App\Student',
            'lectures',
            'lectures_id',
            'students_id'
            );
    }
    public function lecture(){
        return $this->hasOne('App\Lecture', 'id', 'lecture_id')->get();
    }

    public function student(){
        return $this->hasOne('App\Student', 'id', 'student_id')->get();
    }
}

blog/app/Http/Controllers/GradeController.php
<?php

namespace App\Http\Controllers;

use App\Grade;
use App\Http\Requests\GradesRequest;
use App\Lecture;
use App\Student;
use Illuminate\Http\Request;

class GradeController extends Controller
{
    public function __construct()
    {
        $this->middleware('teacher');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lectures = Lecture::all();
        $students = Student::all();

        return view('grades.create', [
            'lectures' => $lectures,
            'students' => $students
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(GradesRequest $request)
    {
        $grade = new Grade();
        $grade->lecture_id = request('lecture_id');
        $grade->student_id = request('student_id');
        $grade->grade = request('grade');
        $grade->save();

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Grade  $grade
     * @return \Illuminate\Http\Response
     */
    public function show(Grade $grade)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Grade  $grade
     * @return \Illuminate\Http\Response
     */
    public function edit(Grade $grade)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Grade  $grade
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Grade $grade)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Grade  $grade
     * @return \Illuminate\Http\Response
     */
    public function destroy(Grade $grade)
    {
        //
    }
}

blog/resources/views/grades/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-md-center">
                <h1>{{__('Giving grade to a student')}}</h1>
            </div>
            <div class="col-md-6">
                <form method="post" action="{{route('grades.store')}}">
                    @csrf
                    <label>{{__('Lecture')}}:</label>
                    <select class="form-control" name="lecture_id" required>
                        <option value="">{{__('Choose lecture')}}</option>
                        @foreach($lectures as $lecture)
                            @if($lecture->id == old('lecture_id'))
                                <option selected value="{{ $lecture->id }}">{{ $lecture->name }}</option>
                            @else
                                <option value="{{ $lecture->id }}">{{ $lecture->name }}</option>
                            @endif
                        @endforeach
                    </select>
                    <label>{{__('Student')}}:</label>
                    <select class="form-control" name="student_id" required>
                        <option value="">{{__('Choose student')}}</option>
                        @foreach($students as $student)
                            @if($student->id == old('student_id'))
                                <option selected value="{{ $student->id }}">
                                    {{ $student->name }}
                                    {{ $student->surname }}
                                </option>
                            @else
                                <option value="{{ $student->id }}">
                                    {{ $student->name }}
                                    {{ $student->surname }}
                                </option>
                            @endif
                        @endforeach
                    </select>
                    <div>
                        <label>{{__('Grade')}}:</label>
                        <input class="form-control" required name="grade" type="number">
                    </div>
                    <div>
                        <input class="col-md-6 mt-3 float-md-right btn-success form-control" type="submit" value="{{__('Add')}}">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection