blog/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('students', 'StudentController');
Route::resource('lectures', 'LectureController');
Route::resource('grades', 'GradeController');

blog/app/Lecture.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lecture extends Model
{
    protected $table = 'lectures';

    protected $guarded =['id'];

    public function lectures(){
        return $this->hasMany('App\Grade', 'lecture_id', 'id');
    }
}

blog/app/Http/Controllers/LectureController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LecturesRequest;
use App\Lecture;
use Illuminate\Http\Request;

class LectureController extends Controller
{
    public function __construct()
    {
        $this->middleware('teacher');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lectures = Lecture::all();

        return view('lectures.index', ['lectures' => $lectures]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('lectures.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Lecture::create($request->all());

        session()->flash('message', 'Added new lecture');
        session()->flash('message-class', 'alert-success');

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Lecture  $lecture
     * @return \Illuminate\Http\Response
     */
    public function show(Lecture $lecture)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Lecture  $lecture
     * @return \Illuminate\Http\Response
     */
    public function edit(Lecture $lecture)
    {
        return view('lectures.edit', ['lecture' => $lecture]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Lecture  $lecture
     * @return \Illuminate\Http\Response
     */
    public function update(LecturesRequest $request, Lecture $lecture)
    {
        $lecture->update($request->all());

        session()->flash('message', 'Updated lecture');
        session()->flash('message-class', 'alert-success');

        return redirect()->route('lectures.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Lecture  $lecture
     * @return \Illuminate\Http\Response
     */
    public function destroy(Lecture $lecture)
    {
        $lecture->delete();

        session()->flash('message', 'Lecture was deleted');
        session()->flash('message-class', 'alert-danger');

        return redirect()->back();
    }
}

blog/resources/views/lectures/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-md-center">
                <h1>{{__('Adding new lecture')}}</h1>
            </div>


            <div class="col-md-6">
                <form method="post" action="{{route('lectures.store')}}">
                    @csrf
                    <div>
                        <label>{{__('Name')}}:</label>
                        <input class="form-control" required name="name" type="text">
                    </div>
                    <div>
                        <label>{{__('Description')}}:</label>
                        <textarea class="form-control" required name="description"></textarea>
                    </div>

                    <div>
                        <input class="col-md-6 mt-3 float-md-right btn-success form-control" type="submit" value="{{__('Add')}}">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/lectures/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-md-center">
                <h1>{{__('Updating lecture')}}: {{$lecture->name}}</h1>
            </div>
            <div class="col-md-6">
                <form method="post" action="{{route('lectures.update', [$lecture->id])}}">
                    @csrf
                    @method('put')
                    <div>
                        <label>{{__('Name')}}:</label>
                        <input class="form-control" name="name" type="text" value="{{$lecture->name}}">
                    </div>
                    <div>
                        <label>{{__('Description')}}:</label>
                        <textarea class="form-control" name="description">{{$lecture->description}}</textarea>
                    </div>
                    <div>
                        <input class="col-md-6 mt-3 float-md-right btn-success form-control" type="submit" value="{{__('Update')}}">
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

blog/resources/views/lectures/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                        <th>
                            {{__('ID')}}
                        </th>
                        <th>
                            {{__('Name')}}
                        </th>
                        <th>
                            {{__('Description')}}
                        </th>
                        <th>
                            {{__('Edit')}}
                        </th>
                        <th>
                            {{__('Delete')}}
                        </th>
                    </thead>
                    <tbody>
                    @foreach($lectures as $lecture)
                        <tr>
                            <td>
                                {{ $lecture->id }}
                            </td>
                            <td>
                                {{ $lecture->name }}
                            </td>
                            <td>
                                {!! $lecture->description !!}
                            </td>
                            <td>
                                <form method="get" action="{{ route('lectures.edit', [$lecture->id]) }}">
                                    <input class="btn btn-success" type="submit" value="Edit">
                                </form>
                            </td>
                            <td>
                                <form method="post" action="{{route('lectures.destroy', [$lecture->id])}}">
                                    @csrf
                                    @method('delete')
                                    <input class="btn btn-danger" type="submit" value="X">
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection